sudo: required
language: python
python:
  - "2.7"
addons:
  chrome: stable
  firefox: latest
env:
  matrix:
    - TEST_BROWSER=firefox SELENIUM_WINDOW_SIZE=1024x768
    - TEST_BROWSER=firefox SELENIUM_WINDOW_SIZE=640x480
    - TEST_BROWSER=chrome SELENIUM_WINDOW_SIZE=1024x768
    - TEST_BROWSER=chrome SELENIUM_WINDOW_SIZE=640x480
    - TEST_BROWSER=firefox-headless SELENIUM_WINDOW_SIZE=1024x768
    - TEST_BROWSER=firefox-headless SELENIUM_WINDOW_SIZE=640x480
    - TEST_BROWSER=chrome-headless SELENIUM_WINDOW_SIZE=1024x768
    - TEST_BROWSER=chrome-headless SELENIUM_WINDOW_SIZE=640x480
  global:
    - DISPLAY=:99.0
install:
  - pip install -r requirements.txt
before_script:
  # Install geckodriver for selenium>=3.0
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  # install chromedriver
  - wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  # launch x frame buffer
  - sh -e /etc/init.d/xvfb start
script:
  - make pep8
  - make flake8
  - make coverage
